<?php

namespace AppBundle\Repository;

/**
 * StudentGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
